//! Hash-parity test: proves the Rust chain hashing matches the
//! server's recordEvent.ts byte-for-byte. Vectors generated by
//! testdata/gen-hash-vectors.ts from the TS source. A divergence here means the
//! server's verifyChain() would reject a valid ingest chain.

use sanctions_ingest::chain::{
    compute_event_hash, compute_payload_hash, stable_stringify, EventHashMaterial, GENESIS_HASH,
};
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct StableVec {
    input: Value,
    out: String,
}
#[derive(Deserialize)]
struct PayloadVec {
    payload: Value,
    hash: String,
}
#[derive(Deserialize)]
struct MaterialJson {
    seq: i64,
    #[serde(rename = "chainId")]
    chain_id: String,
    #[serde(rename = "eventType")]
    event_type: String,
    action: String,
    #[serde(rename = "objectType")]
    object_type: Option<String>,
    #[serde(rename = "objectId")]
    object_id: Option<String>,
    #[serde(rename = "entityId")]
    entity_id: Option<String>,
    #[serde(rename = "actorAccountId")]
    actor_account_id: Option<String>,
    citations: Vec<String>,
    #[serde(rename = "payloadHash")]
    payload_hash: String,
    #[serde(rename = "prevHash")]
    prev_hash: String,
}
#[derive(Deserialize)]
struct EventVec {
    material: MaterialJson,
    hash: String,
}
#[derive(Deserialize)]
struct Fixture {
    #[serde(rename = "genesisHash")]
    genesis_hash: String,
    stable: Vec<StableVec>,
    #[serde(rename = "payloadHash")]
    payload_hash: Vec<PayloadVec>,
    #[serde(rename = "eventHash")]
    event_hash: Vec<EventVec>,
}

#[test]
fn hash_scheme_parity() {
    let raw = include_str!("../testdata/hash-vectors.json");
    let fx: Fixture = serde_json::from_str(raw).expect("hash-vectors.json parses");

    assert_eq!(fx.genesis_hash, GENESIS_HASH, "genesis hash mismatch");

    for v in &fx.stable {
        assert_eq!(stable_stringify(&v.input), v.out, "stableStringify divergence for {:?}", v.input);
    }
    for v in &fx.payload_hash {
        assert_eq!(compute_payload_hash(&v.payload), v.hash, "payloadHash divergence");
    }
    for v in &fx.event_hash {
        let m = EventHashMaterial {
            seq: v.material.seq,
            chain_id: v.material.chain_id.clone(),
            event_type: v.material.event_type.clone(),
            action: v.material.action.clone(),
            object_type: v.material.object_type.clone(),
            object_id: v.material.object_id.clone(),
            entity_id: v.material.entity_id.clone(),
            actor_account_id: v.material.actor_account_id.clone(),
            citations: v.material.citations.clone(),
            payload_hash: v.material.payload_hash.clone(),
            prev_hash: v.material.prev_hash.clone(),
        };
        assert_eq!(compute_event_hash(&m), v.hash, "computeEventHash divergence at seq {}", v.material.seq);
    }
    eprintln!(
        "✓ hash parity: {} stable + {} payload + {} event vectors",
        fx.stable.len(),
        fx.payload_hash.len(),
        fx.event_hash.len()
    );
}
