//! Golden-vector parity test: proves the Rust name-math matches
//! the server's TS `normalize.ts` byte-for-byte. The fixture is generated by
//! testdata/gen-golden-vectors.ts from the SERVER source — regenerate it if the
//! server normaliser ever changes, and this test will catch any drift.

use sanctions_ingest::normalize::{normalize_for_search, phonetic_tokens};
use serde::Deserialize;

#[derive(Deserialize)]
struct Vector {
    input: String,
    norm: String,
    phonetic: Vec<String>,
}

#[test]
fn golden_vector_parity() {
    let raw = include_str!("../testdata/golden-vectors.json");
    let vectors: Vec<Vector> = serde_json::from_str(raw).expect("golden-vectors.json must parse");
    assert!(!vectors.is_empty(), "fixture must not be empty");

    for v in &vectors {
        assert_eq!(
            normalize_for_search(&v.input),
            v.norm,
            "normalize_for_search divergence for input {:?}",
            v.input
        );
        assert_eq!(
            phonetic_tokens(&v.input),
            v.phonetic,
            "phonetic_tokens divergence for input {:?}",
            v.input
        );
    }
    eprintln!("✓ {} golden vectors matched byte-for-byte", vectors.len());
}
